name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['g++', 'clang++']
    env:
      CXX: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make debug
      run: make debug
